# タグが作成された時にドキュメントを生成してnextcloudにアップロードする
name: documentation
on:
  push:
    tags:
      - "*"
jobs:
  generate-doc:
    name: Generate documentation and upload
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/Iron"
      - name: Install yarn
        run: npm install -g yarn
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.17
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
          ${HOME}/.local/bin/poetry config virtualenvs.in-project true
      - name: Install protoc
        env:
          PROTOC_VERSION: "24.2"
        run: |
          curl -L -O https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          unzip protoc-${PROTOC_VERSION}-linux-x86_64.zip
          cp ./bin/protoc /usr/local/bin/.
          chmod +x /usr/local/bin/protoc
      - name: Setup nextcloud-cli
        run: |
          go install github.com/kurusugawa-computer/nextcloud-cli@latest
          nextcloud-cli login -u="${{ secrets.NEXTCLOUD_USERNAME }}" -p="${{ secrets.NEXTCLOUD_PASSWORD }}" ${{ secrets.NEXTCLOUD_ENDPOINT }}
      - name: Generate api documentation
        run: make docs -j$(nproc)
      - name: Upload documentation
        working-directory: ./lib
        run: |
          nextcloud-cli upload -o "${{ secrets.NEXTCLOUD_PREFIX }}${{ github.ref_name }}" docs/_build/html/*
